# Generated by Django 5.1.5 on 2025-02-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="thumbnails/default.png",
                null=True,
                upload_to="thumbnails/",
            ),
        ),
    ]
