# Generated by Django 5.1.5 on 2025-01-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("daily", "일상"),
                            ("travel", "여행"),
                            ("hobby", "취미"),
                            ("cook", "요리"),
                        ],
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("content", models.CharField(max_length=2000, verbose_name="본문")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일자"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="작성일자"),
                ),
            ],
        ),
    ]
